---
- name: Configure RPM System for development
  become: true
  # hosts: rhel   # Development
  hosts: localhost  # Production
  vars_prompt:
    - name: hostname
      prompt: "Enter system hostname"
    - name: primary_user
      prompt: "Enter UNIX username"


  pre_tasks:
    - name: Set System Hostname
      hostname: 
        name: "{{ hostname }}"
      when: ansible_distribution != "Rocky"

    - name: Update Systems
      include_tasks: ./tasks/update.yml

  roles:
    - packages
    - config
    # - wsl
    - gui
    - docker