---
- name: Install Visual Studio Code on Fedora Linux
  hosts: all
  become: yes
  tasks:
    - name: Add Visual Studio Code repository
      yum_repository:
        name: vscode
        description: Visual Studio Code repository
        baseurl: https://packages.microsoft.com/yumrepos/vscode
        gpgcheck: yes
        gpgkey: https://packages.microsoft.com/keys/microsoft.asc
        state: present

    - name: Install Visual Studio Code
      dnf:
        name: code
        state: present
