---
# ADD COPY DOTFILES
- name: Add Visual Studio Code repository
  yum_repository:
    name: vscode
    description: Visual Studio Code repository
    baseurl: https://packages.microsoft.com/yumrepos/vscode
    gpgcheck: yes
    gpgkey: https://packages.microsoft.com/keys/microsoft.asc
    state: present

- name: Install Visual Studio Code
  dnf:
    name: code
    state: present

- name: Install Gnome Tweaks
  dnf:
    name: gnome-tweaks
    state: present

- name: Install Gnome Extensions App
  dnf:
    name: gnome-extensions-app
    state: present

- name: Install ZSH
  dnf:
    name: zsh
    state: present

- name: Install Neofetch
  dnf:
    name: neofetch
    state: present