---
- name: Add Visual Studio Code repository
  yum_repository:
    name: vscode
    description: Visual Studio Code repository
    baseurl: https://packages.microsoft.com/yumrepos/vscode
    gpgcheck: yes
    gpgkey: https://packages.microsoft.com/keys/microsoft.asc
    state: present

- name: Install Visual Studio Code
  dnf:
    name: code
    state: present

- name: Install LibreOffice
  dnf:
    name: libreoffice
    state: present
  when: ansible_distribution != "Rocky"

- name: Install Gnome Tweaks
  dnf:
    name: gnome-tweaks
    state: present

- name: Install Gnome Extensions App
  dnf:
    name: gnome-extensions-app
    state: present

- name: Install ZSH
  dnf:
    name: zsh
    state: present

- name: Install zsh-autosuggestions
  dnf:
    name: zsh-autosuggestions
    state: present
  when: ansible_distribution != "Rocky"

- name: Install Neofetch
  dnf:
    name: neofetch
    state: present

- name: Set ZSH as Shell
  user:
    name: "{{ primary_user }}"
    shell: /bin/zsh

- name: Install Snap
  dnf:
    name: snapd
    state: present

- name: Enable snapd
  ansible.builtin.systemd:
    name: snapd
    state: started
    enabled: yes

- name: Install Spotify via Snap
  snap:
    name: spotify
    state: present
