---
- name: Copy dotfiles
  ansible.builtin.copy:
    src: ../files/dotfiles.tar
    dest: /home/{{ primary_user }}/
    owner: "{{ primary_user }}"
    group: "{{ primary_user }}"
    mode: '0644'
    backup: no

- name: Extract dotfiles
  ansible.builtin.unarchive:
    src: ../files/dotfiles.tar
    dest: /home/{{ primary_user }}/
    remote_src: no

- name: Remove tarball
  ansible.builtin.file:
    path: /home/{{ primary_user }}/dotfiles.tar
    state: absent